name: Action test

on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # prints stuff
      - name: Print hello world
        run: echo "Hello World!"
