name: Release

on:
  push:
    tags:
      - '*'

jobs:
  # Builds for Windows and caches it's artifacts
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./tauri-app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: yarn install
      
      - name: Build
        run: yarn tauri build

      - name: Create artifacts folder
        shell: pwsh
        run: New-Item -Path "windows-artifacts" -ItemType Directory
      
      - name: Create portable artifact in the artifacts folder
        shell: pwsh
        run: ../.github/scripts/windows/desktop-portable-zip.ps1 windows-artifacts

      - name: Move installer artifact to the artifacts folder
        shell: pwsh
        run: Move-Item -Path "./src-tauri/target/release/bundle/msi/*.msi" -Destination windows-artifacts

      - name: Sanity check
        shell: pwsh
        run: dir windows-artifacts

      - name: Cache artifacts
        uses: actions/cache@v3
        with:
          path: ./tauri-app/windows-artifacts
          key: windows-artifacts-cache


  # Builds for Ubuntu and caches it's artifacts
  build-ubuntu:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./tauri-app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
          yarn install
      
      - name: Build
        run: yarn tauri build

      - name: Move generated artifacts to artifacts folder
        run: |
          mkdir ubuntu-artifacts
          mv ./src-tauri/target/release/bundle/appimage/*.AppImage ./ubuntu-artifacts
          mv ./src-tauri/target/release/bundle/deb/*.deb ./ubuntu-artifacts

      - name: Cache artifacts
        uses: actions/cache@v3
        with:
          path: ./tauri-app/ubuntu-artifacts
          key: ubuntu-artifacts-cache


  # Creates a new release with the Windows and Ubuntu artifacts
  create-release:
    needs: [build-windows, build-ubuntu]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Restore Windows artifacts
        uses: actions/cache@v3
        with:
          path: ./tauri-app/windows-artifacts
          key: windows-artifacts-cache

      - name: Restore Ubuntu artifacts
        uses: actions/cache@v3
        with:
          path: ./tauri-app/ubuntu-artifacts
          key: ubuntu-artifacts-cache

      - name: Get tag name
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
     
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ TAG }}
          files: |
            ./tauri-app/windows-artifacts/*
            ./tauri-app/ubuntu-artifacts/*
